management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: ${SERVER_PORT:8501}
springfox:
  documentation:
    swagger:
      v2:
        path: /rest/docs
application:
  account:
    max-transactions: 3
  exchange:
    url: http://api.currencylayer.com/live
    accessKey: 838d5394a997d33a9917f92d1e80b164

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:liquibase/db-changelog.xml
datasource:
  url: ${URL_DATASOURCE:jdbc:mariadb://localhost:3306/demo}
  username: ${DATABASE_USER:root}
  password: ${DATABASE_PWD:password-d}
  driverClassName: org.mariadb.jdbc.Driver
security:
  private-key-path: ${PRIVATE_KEY_PATH:/home/arturo/keys/private_key.der}
  public-key-path:  ${PUPLIC_KEY_PATH:/home/arturo/keys/public_key.der}

